version: '3.7'

services:
  tajinaste-auth:
    image: pedroetb/tajinaste-auth:${IMAGE_TAG:-latest}
    environment:
      - PORT
      - EXPIRY_MINUTES
      - PRIVATE_JWK
      - PGHOST
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
    networks:
      tajinaste-net:
        aliases:
          - auth
      traefik-net:
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: Host:tajinaste.${PUBLIC_HOSTNAME};PathPrefixStrip:/auth
        traefik.backend: tajinaste-auth
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          memory: 32M

networks:
  tajinaste-net:
    name: tajinaste-net

  traefik-net:
    external: true
