version: '3.9'

services:
  tajinaste-auth:
    image: ${IMAGE_NAME:-pedroetb/tajinaste-auth}:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        NODE_IMAGE_TAG:
    environment:
      EXPIRY_MINUTES:
      PRIVATE_JWK:
      PGHOST:
      PGPORT:
      PGUSER:
      PGPASSWORD:
      PGDATABASE:
    networks:
      tajinaste-net:
        aliases:
          - ${TAJINASTE_NET_ALIAS:-auth}
      traefik-net:
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.tajinaste-auth.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.tajinaste-auth.rule: Host(`${TRAEFIK_SUBDOMAIN}.${TRAEFIK_DOMAIN}`) && PathPrefix(`${TRAEFIK_PATHPREFIX}`)
        traefik.http.middlewares.tajinaste-auth-strip-prefix.stripprefix.prefixes: ${TRAEFIK_PATHPREFIX}
        traefik.http.routers.tajinaste-auth.middlewares: tajinaste-auth-strip-prefix
        traefik.http.services.tajinaste-auth.loadbalancer.server.port: ${TRAEFIK_PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  tajinaste-net:
    name: ${TAJINASTE_NET_NAME:-tajinaste-net}
    driver: ${TAJINASTE_NET_DRIVER:-overlay}
    attachable: ${TAJINASTE_NET_ATTACHABLE:-true}

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
